namespace InventTrack
{
    partial class FormManageProduct
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormManageProduct));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.dgvData = new System.Windows.Forms.DataGridView();
            this.btnupdate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnInsert = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnDelete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tbStock = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbDescription = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbsearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.cboCategory = new System.Windows.Forms.ComboBox();
            this.label2 = new System.Windows.Forms.Label();
            this.tbImage = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnSelectFile = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pbImage = new System.Windows.Forms.PictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.dgvData)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbImage)).BeginInit();
            this.SuspendLayout();
            // 
            // dgvData
            // 
            this.dgvData.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvData.BackgroundColor = System.Drawing.Color.White;
            this.dgvData.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.None;
            this.dgvData.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle1.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvData.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvData.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Poppins", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvData.DefaultCellStyle = dataGridViewCellStyle2;
            this.dgvData.GridColor = System.Drawing.Color.White;
            this.dgvData.Location = new System.Drawing.Point(39, 141);
            this.dgvData.Name = "dgvData";
            this.dgvData.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Poppins", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle3.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvData.RowHeadersDefaultCellStyle = dataGridViewCellStyle3;
            this.dgvData.RowHeadersWidth = 51;
            this.dgvData.RowTemplate.Height = 24;
            this.dgvData.Size = new System.Drawing.Size(824, 172);
            this.dgvData.TabIndex = 49;
            this.dgvData.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvData_CellClick);
            // 
            // btnupdate
            // 
            this.btnupdate.AllowAnimations = true;
            this.btnupdate.AllowMouseEffects = true;
            this.btnupdate.AllowToggling = false;
            this.btnupdate.AnimationSpeed = 200;
            this.btnupdate.AutoGenerateColors = false;
            this.btnupdate.AutoRoundBorders = false;
            this.btnupdate.AutoSizeLeftIcon = true;
            this.btnupdate.AutoSizeRightIcon = true;
            this.btnupdate.BackColor = System.Drawing.Color.Transparent;
            this.btnupdate.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnupdate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnupdate.BackgroundImage")));
            this.btnupdate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnupdate.ButtonText = "Update";
            this.btnupdate.ButtonTextMarginLeft = 0;
            this.btnupdate.ColorContrastOnClick = 45;
            this.btnupdate.ColorContrastOnHover = 45;
            this.btnupdate.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnupdate.CustomizableEdges = borderEdges1;
            this.btnupdate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnupdate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnupdate.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnupdate.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnupdate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnupdate.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnupdate.ForeColor = System.Drawing.Color.White;
            this.btnupdate.IconLeft = null;
            this.btnupdate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnupdate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnupdate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnupdate.IconMarginLeft = 11;
            this.btnupdate.IconPadding = 10;
            this.btnupdate.IconRight = null;
            this.btnupdate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnupdate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnupdate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnupdate.IconSize = 25;
            this.btnupdate.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnupdate.IdleBorderRadius = 0;
            this.btnupdate.IdleBorderThickness = 0;
            this.btnupdate.IdleFillColor = System.Drawing.Color.Empty;
            this.btnupdate.IdleIconLeftImage = null;
            this.btnupdate.IdleIconRightImage = null;
            this.btnupdate.IndicateFocus = false;
            this.btnupdate.Location = new System.Drawing.Point(380, 556);
            this.btnupdate.Name = "btnupdate";
            this.btnupdate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnupdate.OnDisabledState.BorderRadius = 32;
            this.btnupdate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnupdate.OnDisabledState.BorderThickness = 1;
            this.btnupdate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnupdate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnupdate.OnDisabledState.IconLeftImage = null;
            this.btnupdate.OnDisabledState.IconRightImage = null;
            this.btnupdate.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnupdate.onHoverState.BorderRadius = 32;
            this.btnupdate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnupdate.onHoverState.BorderThickness = 1;
            this.btnupdate.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnupdate.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnupdate.onHoverState.IconLeftImage = null;
            this.btnupdate.onHoverState.IconRightImage = null;
            this.btnupdate.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnupdate.OnIdleState.BorderRadius = 32;
            this.btnupdate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnupdate.OnIdleState.BorderThickness = 1;
            this.btnupdate.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnupdate.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnupdate.OnIdleState.IconLeftImage = null;
            this.btnupdate.OnIdleState.IconRightImage = null;
            this.btnupdate.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnupdate.OnPressedState.BorderRadius = 32;
            this.btnupdate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnupdate.OnPressedState.BorderThickness = 1;
            this.btnupdate.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnupdate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnupdate.OnPressedState.IconLeftImage = null;
            this.btnupdate.OnPressedState.IconRightImage = null;
            this.btnupdate.Size = new System.Drawing.Size(140, 39);
            this.btnupdate.TabIndex = 47;
            this.btnupdate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnupdate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnupdate.TextMarginLeft = 0;
            this.btnupdate.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnupdate.UseDefaultRadiusAndThickness = true;
            this.btnupdate.Click += new System.EventHandler(this.btnupdate_Click);
            // 
            // btnInsert
            // 
            this.btnInsert.AllowAnimations = true;
            this.btnInsert.AllowMouseEffects = true;
            this.btnInsert.AllowToggling = false;
            this.btnInsert.AnimationSpeed = 200;
            this.btnInsert.AutoGenerateColors = false;
            this.btnInsert.AutoRoundBorders = false;
            this.btnInsert.AutoSizeLeftIcon = true;
            this.btnInsert.AutoSizeRightIcon = true;
            this.btnInsert.BackColor = System.Drawing.Color.Transparent;
            this.btnInsert.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnInsert.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnInsert.BackgroundImage")));
            this.btnInsert.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInsert.ButtonText = "Insert";
            this.btnInsert.ButtonTextMarginLeft = 0;
            this.btnInsert.ColorContrastOnClick = 45;
            this.btnInsert.ColorContrastOnHover = 45;
            this.btnInsert.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnInsert.CustomizableEdges = borderEdges2;
            this.btnInsert.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnInsert.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInsert.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnInsert.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnInsert.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnInsert.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnInsert.ForeColor = System.Drawing.Color.White;
            this.btnInsert.IconLeft = null;
            this.btnInsert.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnInsert.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnInsert.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnInsert.IconMarginLeft = 11;
            this.btnInsert.IconPadding = 10;
            this.btnInsert.IconRight = null;
            this.btnInsert.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnInsert.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnInsert.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnInsert.IconSize = 25;
            this.btnInsert.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnInsert.IdleBorderRadius = 0;
            this.btnInsert.IdleBorderThickness = 0;
            this.btnInsert.IdleFillColor = System.Drawing.Color.Empty;
            this.btnInsert.IdleIconLeftImage = null;
            this.btnInsert.IdleIconRightImage = null;
            this.btnInsert.IndicateFocus = false;
            this.btnInsert.Location = new System.Drawing.Point(211, 556);
            this.btnInsert.Name = "btnInsert";
            this.btnInsert.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInsert.OnDisabledState.BorderRadius = 32;
            this.btnInsert.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInsert.OnDisabledState.BorderThickness = 1;
            this.btnInsert.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInsert.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInsert.OnDisabledState.IconLeftImage = null;
            this.btnInsert.OnDisabledState.IconRightImage = null;
            this.btnInsert.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnInsert.onHoverState.BorderRadius = 32;
            this.btnInsert.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInsert.onHoverState.BorderThickness = 1;
            this.btnInsert.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnInsert.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnInsert.onHoverState.IconLeftImage = null;
            this.btnInsert.onHoverState.IconRightImage = null;
            this.btnInsert.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnInsert.OnIdleState.BorderRadius = 32;
            this.btnInsert.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInsert.OnIdleState.BorderThickness = 1;
            this.btnInsert.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnInsert.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnInsert.OnIdleState.IconLeftImage = null;
            this.btnInsert.OnIdleState.IconRightImage = null;
            this.btnInsert.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnInsert.OnPressedState.BorderRadius = 32;
            this.btnInsert.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInsert.OnPressedState.BorderThickness = 1;
            this.btnInsert.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnInsert.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnInsert.OnPressedState.IconLeftImage = null;
            this.btnInsert.OnPressedState.IconRightImage = null;
            this.btnInsert.Size = new System.Drawing.Size(140, 39);
            this.btnInsert.TabIndex = 46;
            this.btnInsert.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnInsert.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnInsert.TextMarginLeft = 0;
            this.btnInsert.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnInsert.UseDefaultRadiusAndThickness = true;
            this.btnInsert.Click += new System.EventHandler(this.btnInsert_Click);
            // 
            // btnDelete
            // 
            this.btnDelete.AllowAnimations = true;
            this.btnDelete.AllowMouseEffects = true;
            this.btnDelete.AllowToggling = false;
            this.btnDelete.AnimationSpeed = 200;
            this.btnDelete.AutoGenerateColors = false;
            this.btnDelete.AutoRoundBorders = false;
            this.btnDelete.AutoSizeLeftIcon = true;
            this.btnDelete.AutoSizeRightIcon = true;
            this.btnDelete.BackColor = System.Drawing.Color.Transparent;
            this.btnDelete.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnDelete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDelete.BackgroundImage")));
            this.btnDelete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.ButtonText = "Delete";
            this.btnDelete.ButtonTextMarginLeft = 0;
            this.btnDelete.ColorContrastOnClick = 45;
            this.btnDelete.ColorContrastOnHover = 45;
            this.btnDelete.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnDelete.CustomizableEdges = borderEdges3;
            this.btnDelete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDelete.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelete.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnDelete.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnDelete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDelete.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDelete.ForeColor = System.Drawing.Color.White;
            this.btnDelete.IconLeft = null;
            this.btnDelete.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDelete.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelete.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDelete.IconMarginLeft = 11;
            this.btnDelete.IconPadding = 10;
            this.btnDelete.IconRight = null;
            this.btnDelete.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDelete.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelete.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDelete.IconSize = 25;
            this.btnDelete.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnDelete.IdleBorderRadius = 0;
            this.btnDelete.IdleBorderThickness = 0;
            this.btnDelete.IdleFillColor = System.Drawing.Color.Empty;
            this.btnDelete.IdleIconLeftImage = null;
            this.btnDelete.IdleIconRightImage = null;
            this.btnDelete.IndicateFocus = false;
            this.btnDelete.Location = new System.Drawing.Point(552, 556);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelete.OnDisabledState.BorderRadius = 32;
            this.btnDelete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.OnDisabledState.BorderThickness = 1;
            this.btnDelete.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDelete.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDelete.OnDisabledState.IconLeftImage = null;
            this.btnDelete.OnDisabledState.IconRightImage = null;
            this.btnDelete.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.btnDelete.onHoverState.BorderRadius = 32;
            this.btnDelete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.onHoverState.BorderThickness = 1;
            this.btnDelete.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnDelete.onHoverState.ForeColor = System.Drawing.Color.Red;
            this.btnDelete.onHoverState.IconLeftImage = null;
            this.btnDelete.onHoverState.IconRightImage = null;
            this.btnDelete.OnIdleState.BorderColor = System.Drawing.Color.Red;
            this.btnDelete.OnIdleState.BorderRadius = 32;
            this.btnDelete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.OnIdleState.BorderThickness = 1;
            this.btnDelete.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.btnDelete.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDelete.OnIdleState.IconLeftImage = null;
            this.btnDelete.OnIdleState.IconRightImage = null;
            this.btnDelete.OnPressedState.BorderColor = System.Drawing.Color.Red;
            this.btnDelete.OnPressedState.BorderRadius = 32;
            this.btnDelete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.OnPressedState.BorderThickness = 1;
            this.btnDelete.OnPressedState.FillColor = System.Drawing.Color.Red;
            this.btnDelete.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDelete.OnPressedState.IconLeftImage = null;
            this.btnDelete.OnPressedState.IconRightImage = null;
            this.btnDelete.Size = new System.Drawing.Size(140, 39);
            this.btnDelete.TabIndex = 45;
            this.btnDelete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDelete.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDelete.TextMarginLeft = 0;
            this.btnDelete.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDelete.UseDefaultRadiusAndThickness = true;
            this.btnDelete.Click += new System.EventHandler(this.btnDelete_Click);
            // 
            // btnCancel
            // 
            this.btnCancel.AllowAnimations = true;
            this.btnCancel.AllowMouseEffects = true;
            this.btnCancel.AllowToggling = false;
            this.btnCancel.AnimationSpeed = 200;
            this.btnCancel.AutoGenerateColors = false;
            this.btnCancel.AutoRoundBorders = false;
            this.btnCancel.AutoSizeLeftIcon = true;
            this.btnCancel.AutoSizeRightIcon = true;
            this.btnCancel.BackColor = System.Drawing.Color.Transparent;
            this.btnCancel.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCancel.BackgroundImage")));
            this.btnCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.ButtonText = "Cancel";
            this.btnCancel.ButtonTextMarginLeft = 0;
            this.btnCancel.ColorContrastOnClick = 45;
            this.btnCancel.ColorContrastOnHover = 45;
            this.btnCancel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnCancel.CustomizableEdges = borderEdges4;
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnCancel.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCancel.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.ForeColor = System.Drawing.Color.White;
            this.btnCancel.IconLeft = null;
            this.btnCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCancel.IconMarginLeft = 11;
            this.btnCancel.IconPadding = 10;
            this.btnCancel.IconRight = null;
            this.btnCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCancel.IconSize = 25;
            this.btnCancel.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnCancel.IdleBorderRadius = 0;
            this.btnCancel.IdleBorderThickness = 0;
            this.btnCancel.IdleFillColor = System.Drawing.Color.Empty;
            this.btnCancel.IdleIconLeftImage = null;
            this.btnCancel.IdleIconRightImage = null;
            this.btnCancel.IndicateFocus = false;
            this.btnCancel.Location = new System.Drawing.Point(468, 556);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.OnDisabledState.BorderRadius = 32;
            this.btnCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnDisabledState.BorderThickness = 1;
            this.btnCancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.OnDisabledState.IconLeftImage = null;
            this.btnCancel.OnDisabledState.IconRightImage = null;
            this.btnCancel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnCancel.onHoverState.BorderRadius = 32;
            this.btnCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.onHoverState.BorderThickness = 1;
            this.btnCancel.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnCancel.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnCancel.onHoverState.IconLeftImage = null;
            this.btnCancel.onHoverState.IconRightImage = null;
            this.btnCancel.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnCancel.OnIdleState.BorderRadius = 32;
            this.btnCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnIdleState.BorderThickness = 1;
            this.btnCancel.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnCancel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.OnIdleState.IconLeftImage = null;
            this.btnCancel.OnIdleState.IconRightImage = null;
            this.btnCancel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnCancel.OnPressedState.BorderRadius = 32;
            this.btnCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnPressedState.BorderThickness = 1;
            this.btnCancel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnCancel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.OnPressedState.IconLeftImage = null;
            this.btnCancel.OnPressedState.IconRightImage = null;
            this.btnCancel.Size = new System.Drawing.Size(140, 39);
            this.btnCancel.TabIndex = 44;
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCancel.TextMarginLeft = 0;
            this.btnCancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCancel.UseDefaultRadiusAndThickness = true;
            // 
            // btnSave
            // 
            this.btnSave.AllowAnimations = true;
            this.btnSave.AllowMouseEffects = true;
            this.btnSave.AllowToggling = false;
            this.btnSave.AnimationSpeed = 200;
            this.btnSave.AutoGenerateColors = false;
            this.btnSave.AutoRoundBorders = false;
            this.btnSave.AutoSizeLeftIcon = true;
            this.btnSave.AutoSizeRightIcon = true;
            this.btnSave.BackColor = System.Drawing.Color.Transparent;
            this.btnSave.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSave.BackgroundImage")));
            this.btnSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.ButtonText = "Save";
            this.btnSave.ButtonTextMarginLeft = 0;
            this.btnSave.ColorContrastOnClick = 45;
            this.btnSave.ColorContrastOnHover = 45;
            this.btnSave.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnSave.CustomizableEdges = borderEdges5;
            this.btnSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnSave.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSave.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSave.ForeColor = System.Drawing.Color.White;
            this.btnSave.IconLeft = null;
            this.btnSave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSave.IconMarginLeft = 11;
            this.btnSave.IconPadding = 10;
            this.btnSave.IconRight = null;
            this.btnSave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSave.IconSize = 25;
            this.btnSave.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnSave.IdleBorderRadius = 0;
            this.btnSave.IdleBorderThickness = 0;
            this.btnSave.IdleFillColor = System.Drawing.Color.Empty;
            this.btnSave.IdleIconLeftImage = null;
            this.btnSave.IdleIconRightImage = null;
            this.btnSave.IndicateFocus = false;
            this.btnSave.Location = new System.Drawing.Point(299, 556);
            this.btnSave.Name = "btnSave";
            this.btnSave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.OnDisabledState.BorderRadius = 32;
            this.btnSave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnDisabledState.BorderThickness = 1;
            this.btnSave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.OnDisabledState.IconLeftImage = null;
            this.btnSave.OnDisabledState.IconRightImage = null;
            this.btnSave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.BorderRadius = 32;
            this.btnSave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.onHoverState.BorderThickness = 1;
            this.btnSave.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnSave.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.IconLeftImage = null;
            this.btnSave.onHoverState.IconRightImage = null;
            this.btnSave.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.OnIdleState.BorderRadius = 32;
            this.btnSave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnIdleState.BorderThickness = 1;
            this.btnSave.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnIdleState.IconLeftImage = null;
            this.btnSave.OnIdleState.IconRightImage = null;
            this.btnSave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSave.OnPressedState.BorderRadius = 32;
            this.btnSave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnPressedState.BorderThickness = 1;
            this.btnSave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnPressedState.IconLeftImage = null;
            this.btnSave.OnPressedState.IconRightImage = null;
            this.btnSave.Size = new System.Drawing.Size(140, 39);
            this.btnSave.TabIndex = 43;
            this.btnSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSave.TextMarginLeft = 0;
            this.btnSave.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSave.UseDefaultRadiusAndThickness = true;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // tbStock
            // 
            this.tbStock.AcceptsReturn = false;
            this.tbStock.AcceptsTab = false;
            this.tbStock.AnimationSpeed = 200;
            this.tbStock.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbStock.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbStock.AutoSizeHeight = true;
            this.tbStock.BackColor = System.Drawing.Color.Transparent;
            this.tbStock.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbStock.BackgroundImage")));
            this.tbStock.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbStock.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbStock.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbStock.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbStock.BorderRadius = 10;
            this.tbStock.BorderThickness = 1;
            this.tbStock.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbStock.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbStock.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbStock.DefaultText = "";
            this.tbStock.FillColor = System.Drawing.Color.White;
            this.tbStock.ForeColor = System.Drawing.Color.Black;
            this.tbStock.HideSelection = true;
            this.tbStock.IconLeft = null;
            this.tbStock.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbStock.IconPadding = 10;
            this.tbStock.IconRight = null;
            this.tbStock.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbStock.Lines = new string[0];
            this.tbStock.Location = new System.Drawing.Point(299, 339);
            this.tbStock.MaxLength = 32767;
            this.tbStock.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbStock.Modified = false;
            this.tbStock.Multiline = false;
            this.tbStock.Name = "tbStock";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbStock.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbStock.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbStock.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbStock.OnIdleState = stateProperties4;
            this.tbStock.Padding = new System.Windows.Forms.Padding(3);
            this.tbStock.PasswordChar = '\0';
            this.tbStock.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbStock.PlaceholderText = "Stock";
            this.tbStock.ReadOnly = false;
            this.tbStock.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbStock.SelectedText = "";
            this.tbStock.SelectionLength = 0;
            this.tbStock.SelectionStart = 0;
            this.tbStock.ShortcutsEnabled = true;
            this.tbStock.Size = new System.Drawing.Size(221, 43);
            this.tbStock.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbStock.TabIndex = 41;
            this.tbStock.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbStock.TextMarginBottom = 0;
            this.tbStock.TextMarginLeft = 5;
            this.tbStock.TextMarginTop = 0;
            this.tbStock.TextPlaceholder = "Stock";
            this.tbStock.UseSystemPasswordChar = false;
            this.tbStock.WordWrap = true;
            // 
            // tbPrice
            // 
            this.tbPrice.AcceptsReturn = false;
            this.tbPrice.AcceptsTab = false;
            this.tbPrice.AnimationSpeed = 200;
            this.tbPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbPrice.AutoSizeHeight = true;
            this.tbPrice.BackColor = System.Drawing.Color.Transparent;
            this.tbPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbPrice.BackgroundImage")));
            this.tbPrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbPrice.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbPrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbPrice.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbPrice.BorderRadius = 10;
            this.tbPrice.BorderThickness = 1;
            this.tbPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPrice.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbPrice.DefaultText = "";
            this.tbPrice.FillColor = System.Drawing.Color.White;
            this.tbPrice.ForeColor = System.Drawing.Color.Black;
            this.tbPrice.HideSelection = true;
            this.tbPrice.IconLeft = null;
            this.tbPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPrice.IconPadding = 10;
            this.tbPrice.IconRight = null;
            this.tbPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPrice.Lines = new string[0];
            this.tbPrice.Location = new System.Drawing.Point(39, 460);
            this.tbPrice.MaxLength = 32767;
            this.tbPrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbPrice.Modified = false;
            this.tbPrice.Multiline = false;
            this.tbPrice.Name = "tbPrice";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPrice.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbPrice.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPrice.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPrice.OnIdleState = stateProperties8;
            this.tbPrice.Padding = new System.Windows.Forms.Padding(3);
            this.tbPrice.PasswordChar = '\0';
            this.tbPrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbPrice.PlaceholderText = "Price";
            this.tbPrice.ReadOnly = false;
            this.tbPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbPrice.SelectedText = "";
            this.tbPrice.SelectionLength = 0;
            this.tbPrice.SelectionStart = 0;
            this.tbPrice.ShortcutsEnabled = true;
            this.tbPrice.Size = new System.Drawing.Size(221, 43);
            this.tbPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbPrice.TabIndex = 40;
            this.tbPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbPrice.TextMarginBottom = 0;
            this.tbPrice.TextMarginLeft = 5;
            this.tbPrice.TextMarginTop = 0;
            this.tbPrice.TextPlaceholder = "Price";
            this.tbPrice.UseSystemPasswordChar = false;
            this.tbPrice.WordWrap = true;
            // 
            // tbDescription
            // 
            this.tbDescription.AcceptsReturn = false;
            this.tbDescription.AcceptsTab = false;
            this.tbDescription.AnimationSpeed = 200;
            this.tbDescription.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbDescription.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbDescription.AutoSizeHeight = true;
            this.tbDescription.BackColor = System.Drawing.Color.Transparent;
            this.tbDescription.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbDescription.BackgroundImage")));
            this.tbDescription.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbDescription.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbDescription.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbDescription.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbDescription.BorderRadius = 10;
            this.tbDescription.BorderThickness = 1;
            this.tbDescription.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbDescription.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbDescription.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbDescription.DefaultText = "";
            this.tbDescription.FillColor = System.Drawing.Color.White;
            this.tbDescription.ForeColor = System.Drawing.Color.Black;
            this.tbDescription.HideSelection = true;
            this.tbDescription.IconLeft = null;
            this.tbDescription.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbDescription.IconPadding = 10;
            this.tbDescription.IconRight = null;
            this.tbDescription.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbDescription.Lines = new string[0];
            this.tbDescription.Location = new System.Drawing.Point(39, 399);
            this.tbDescription.MaxLength = 32767;
            this.tbDescription.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbDescription.Modified = false;
            this.tbDescription.Multiline = false;
            this.tbDescription.Name = "tbDescription";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbDescription.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbDescription.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbDescription.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbDescription.OnIdleState = stateProperties12;
            this.tbDescription.Padding = new System.Windows.Forms.Padding(3);
            this.tbDescription.PasswordChar = '\0';
            this.tbDescription.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbDescription.PlaceholderText = "Description";
            this.tbDescription.ReadOnly = false;
            this.tbDescription.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbDescription.SelectedText = "";
            this.tbDescription.SelectionLength = 0;
            this.tbDescription.SelectionStart = 0;
            this.tbDescription.ShortcutsEnabled = true;
            this.tbDescription.Size = new System.Drawing.Size(221, 43);
            this.tbDescription.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbDescription.TabIndex = 38;
            this.tbDescription.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbDescription.TextMarginBottom = 0;
            this.tbDescription.TextMarginLeft = 5;
            this.tbDescription.TextMarginTop = 0;
            this.tbDescription.TextPlaceholder = "Description";
            this.tbDescription.UseSystemPasswordChar = false;
            this.tbDescription.WordWrap = true;
            // 
            // tbName
            // 
            this.tbName.AcceptsReturn = false;
            this.tbName.AcceptsTab = false;
            this.tbName.AnimationSpeed = 200;
            this.tbName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbName.AutoSizeHeight = true;
            this.tbName.BackColor = System.Drawing.Color.Transparent;
            this.tbName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbName.BackgroundImage")));
            this.tbName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbName.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbName.BorderRadius = 10;
            this.tbName.BorderThickness = 1;
            this.tbName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbName.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbName.DefaultText = "";
            this.tbName.FillColor = System.Drawing.Color.White;
            this.tbName.ForeColor = System.Drawing.Color.Black;
            this.tbName.HideSelection = true;
            this.tbName.IconLeft = null;
            this.tbName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbName.IconPadding = 10;
            this.tbName.IconRight = null;
            this.tbName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbName.Lines = new string[0];
            this.tbName.Location = new System.Drawing.Point(39, 339);
            this.tbName.MaxLength = 32767;
            this.tbName.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbName.Modified = false;
            this.tbName.Multiline = false;
            this.tbName.Name = "tbName";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbName.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbName.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbName.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbName.OnIdleState = stateProperties16;
            this.tbName.Padding = new System.Windows.Forms.Padding(3);
            this.tbName.PasswordChar = '\0';
            this.tbName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbName.PlaceholderText = "Name";
            this.tbName.ReadOnly = false;
            this.tbName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbName.SelectedText = "";
            this.tbName.SelectionLength = 0;
            this.tbName.SelectionStart = 0;
            this.tbName.ShortcutsEnabled = true;
            this.tbName.Size = new System.Drawing.Size(221, 43);
            this.tbName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbName.TabIndex = 37;
            this.tbName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbName.TextMarginBottom = 0;
            this.tbName.TextMarginLeft = 5;
            this.tbName.TextMarginTop = 0;
            this.tbName.TextPlaceholder = "Name";
            this.tbName.UseSystemPasswordChar = false;
            this.tbName.WordWrap = true;
            // 
            // tbsearch
            // 
            this.tbsearch.AcceptsReturn = false;
            this.tbsearch.AcceptsTab = false;
            this.tbsearch.AnimationSpeed = 200;
            this.tbsearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbsearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbsearch.AutoSizeHeight = true;
            this.tbsearch.BackColor = System.Drawing.Color.Transparent;
            this.tbsearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbsearch.BackgroundImage")));
            this.tbsearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbsearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbsearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbsearch.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbsearch.BorderRadius = 10;
            this.tbsearch.BorderThickness = 1;
            this.tbsearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbsearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbsearch.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbsearch.DefaultText = "";
            this.tbsearch.FillColor = System.Drawing.Color.White;
            this.tbsearch.HideSelection = true;
            this.tbsearch.IconLeft = ((System.Drawing.Image)(resources.GetObject("tbsearch.IconLeft")));
            this.tbsearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbsearch.IconPadding = 10;
            this.tbsearch.IconRight = null;
            this.tbsearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbsearch.Lines = new string[0];
            this.tbsearch.Location = new System.Drawing.Point(39, 78);
            this.tbsearch.MaxLength = 32767;
            this.tbsearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbsearch.Modified = false;
            this.tbsearch.Multiline = false;
            this.tbsearch.Name = "tbsearch";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbsearch.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbsearch.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbsearch.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbsearch.OnIdleState = stateProperties20;
            this.tbsearch.Padding = new System.Windows.Forms.Padding(3);
            this.tbsearch.PasswordChar = '\0';
            this.tbsearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbsearch.PlaceholderText = "Search by Name";
            this.tbsearch.ReadOnly = false;
            this.tbsearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbsearch.SelectedText = "";
            this.tbsearch.SelectionLength = 0;
            this.tbsearch.SelectionStart = 0;
            this.tbsearch.ShortcutsEnabled = true;
            this.tbsearch.Size = new System.Drawing.Size(236, 43);
            this.tbsearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbsearch.TabIndex = 36;
            this.tbsearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbsearch.TextMarginBottom = 0;
            this.tbsearch.TextMarginLeft = 15;
            this.tbsearch.TextMarginTop = 0;
            this.tbsearch.TextPlaceholder = "Search by Name";
            this.tbsearch.UseSystemPasswordChar = false;
            this.tbsearch.WordWrap = true;
            this.tbsearch.TextChanged += new System.EventHandler(this.tbsearch_TextChanged);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Poppins", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.Black;
            this.label1.Location = new System.Drawing.Point(290, 22);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(260, 50);
            this.label1.TabIndex = 35;
            this.label1.Text = "Manage Product";
            // 
            // cboCategory
            // 
            this.cboCategory.FormattingEnabled = true;
            this.cboCategory.Location = new System.Drawing.Point(299, 419);
            this.cboCategory.Name = "cboCategory";
            this.cboCategory.Size = new System.Drawing.Size(221, 24);
            this.cboCategory.TabIndex = 50;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Poppins SemiBold", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(73)))), ((int)(((byte)(73)))), ((int)(((byte)(73)))));
            this.label2.Location = new System.Drawing.Point(295, 393);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(72, 23);
            this.label2.TabIndex = 51;
            this.label2.Text = "Category";
            // 
            // tbImage
            // 
            this.tbImage.AcceptsReturn = false;
            this.tbImage.AcceptsTab = false;
            this.tbImage.AnimationSpeed = 200;
            this.tbImage.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbImage.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbImage.AutoSizeHeight = true;
            this.tbImage.BackColor = System.Drawing.Color.Transparent;
            this.tbImage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbImage.BackgroundImage")));
            this.tbImage.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbImage.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbImage.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbImage.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbImage.BorderRadius = 10;
            this.tbImage.BorderThickness = 1;
            this.tbImage.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbImage.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbImage.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbImage.DefaultText = "";
            this.tbImage.FillColor = System.Drawing.Color.White;
            this.tbImage.ForeColor = System.Drawing.Color.Black;
            this.tbImage.HideSelection = true;
            this.tbImage.IconLeft = null;
            this.tbImage.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbImage.IconPadding = 10;
            this.tbImage.IconRight = null;
            this.tbImage.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbImage.Lines = new string[0];
            this.tbImage.Location = new System.Drawing.Point(299, 460);
            this.tbImage.MaxLength = 32767;
            this.tbImage.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbImage.Modified = false;
            this.tbImage.Multiline = false;
            this.tbImage.Name = "tbImage";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbImage.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbImage.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbImage.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Black;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbImage.OnIdleState = stateProperties24;
            this.tbImage.Padding = new System.Windows.Forms.Padding(3);
            this.tbImage.PasswordChar = '\0';
            this.tbImage.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbImage.PlaceholderText = "Image File";
            this.tbImage.ReadOnly = false;
            this.tbImage.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbImage.SelectedText = "";
            this.tbImage.SelectionLength = 0;
            this.tbImage.SelectionStart = 0;
            this.tbImage.ShortcutsEnabled = true;
            this.tbImage.Size = new System.Drawing.Size(221, 43);
            this.tbImage.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbImage.TabIndex = 52;
            this.tbImage.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbImage.TextMarginBottom = 0;
            this.tbImage.TextMarginLeft = 5;
            this.tbImage.TextMarginTop = 0;
            this.tbImage.TextPlaceholder = "Image File";
            this.tbImage.UseSystemPasswordChar = false;
            this.tbImage.WordWrap = true;
            // 
            // btnSelectFile
            // 
            this.btnSelectFile.AllowAnimations = true;
            this.btnSelectFile.AllowMouseEffects = true;
            this.btnSelectFile.AllowToggling = false;
            this.btnSelectFile.AnimationSpeed = 200;
            this.btnSelectFile.AutoGenerateColors = false;
            this.btnSelectFile.AutoRoundBorders = false;
            this.btnSelectFile.AutoSizeLeftIcon = true;
            this.btnSelectFile.AutoSizeRightIcon = true;
            this.btnSelectFile.BackColor = System.Drawing.Color.Transparent;
            this.btnSelectFile.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnSelectFile.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSelectFile.BackgroundImage")));
            this.btnSelectFile.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSelectFile.ButtonText = "Select File";
            this.btnSelectFile.ButtonTextMarginLeft = 0;
            this.btnSelectFile.ColorContrastOnClick = 45;
            this.btnSelectFile.ColorContrastOnHover = 45;
            this.btnSelectFile.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnSelectFile.CustomizableEdges = borderEdges6;
            this.btnSelectFile.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSelectFile.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSelectFile.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnSelectFile.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnSelectFile.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSelectFile.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSelectFile.ForeColor = System.Drawing.Color.White;
            this.btnSelectFile.IconLeft = null;
            this.btnSelectFile.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSelectFile.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSelectFile.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSelectFile.IconMarginLeft = 11;
            this.btnSelectFile.IconPadding = 10;
            this.btnSelectFile.IconRight = null;
            this.btnSelectFile.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSelectFile.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSelectFile.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSelectFile.IconSize = 25;
            this.btnSelectFile.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnSelectFile.IdleBorderRadius = 0;
            this.btnSelectFile.IdleBorderThickness = 0;
            this.btnSelectFile.IdleFillColor = System.Drawing.Color.Empty;
            this.btnSelectFile.IdleIconLeftImage = null;
            this.btnSelectFile.IdleIconRightImage = null;
            this.btnSelectFile.IndicateFocus = false;
            this.btnSelectFile.Location = new System.Drawing.Point(591, 464);
            this.btnSelectFile.Name = "btnSelectFile";
            this.btnSelectFile.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSelectFile.OnDisabledState.BorderRadius = 32;
            this.btnSelectFile.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSelectFile.OnDisabledState.BorderThickness = 1;
            this.btnSelectFile.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSelectFile.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSelectFile.OnDisabledState.IconLeftImage = null;
            this.btnSelectFile.OnDisabledState.IconRightImage = null;
            this.btnSelectFile.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSelectFile.onHoverState.BorderRadius = 32;
            this.btnSelectFile.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSelectFile.onHoverState.BorderThickness = 1;
            this.btnSelectFile.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnSelectFile.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSelectFile.onHoverState.IconLeftImage = null;
            this.btnSelectFile.onHoverState.IconRightImage = null;
            this.btnSelectFile.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSelectFile.OnIdleState.BorderRadius = 32;
            this.btnSelectFile.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSelectFile.OnIdleState.BorderThickness = 1;
            this.btnSelectFile.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSelectFile.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSelectFile.OnIdleState.IconLeftImage = null;
            this.btnSelectFile.OnIdleState.IconRightImage = null;
            this.btnSelectFile.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSelectFile.OnPressedState.BorderRadius = 32;
            this.btnSelectFile.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSelectFile.OnPressedState.BorderThickness = 1;
            this.btnSelectFile.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSelectFile.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSelectFile.OnPressedState.IconLeftImage = null;
            this.btnSelectFile.OnPressedState.IconRightImage = null;
            this.btnSelectFile.Size = new System.Drawing.Size(214, 39);
            this.btnSelectFile.TabIndex = 54;
            this.btnSelectFile.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSelectFile.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSelectFile.TextMarginLeft = 0;
            this.btnSelectFile.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSelectFile.UseDefaultRadiusAndThickness = true;
            this.btnSelectFile.Click += new System.EventHandler(this.btnSelectFile_Click);
            // 
            // pbImage
            // 
            this.pbImage.Location = new System.Drawing.Point(591, 339);
            this.pbImage.Name = "pbImage";
            this.pbImage.Size = new System.Drawing.Size(214, 103);
            this.pbImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbImage.TabIndex = 55;
            this.pbImage.TabStop = false;
            // 
            // FormManageProduct
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(120F, 120F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(902, 654);
            this.Controls.Add(this.pbImage);
            this.Controls.Add(this.btnSelectFile);
            this.Controls.Add(this.tbImage);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.cboCategory);
            this.Controls.Add(this.dgvData);
            this.Controls.Add(this.btnupdate);
            this.Controls.Add(this.btnInsert);
            this.Controls.Add(this.btnDelete);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnSave);
            this.Controls.Add(this.tbStock);
            this.Controls.Add(this.tbPrice);
            this.Controls.Add(this.tbDescription);
            this.Controls.Add(this.tbName);
            this.Controls.Add(this.tbsearch);
            this.Controls.Add(this.label1);
            this.ForeColor = System.Drawing.SystemColors.ControlText;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormManageProduct";
            this.Text = "FormManageProduct";
            this.Load += new System.EventHandler(this.FormManageProduct_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dgvData)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbImage)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.DataGridView dgvData;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnupdate;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnInsert;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDelete;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCancel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSave;
        private Bunifu.UI.WinForms.BunifuTextBox tbStock;
        private Bunifu.UI.WinForms.BunifuTextBox tbPrice;
        private Bunifu.UI.WinForms.BunifuTextBox tbDescription;
        private Bunifu.UI.WinForms.BunifuTextBox tbName;
        private Bunifu.UI.WinForms.BunifuTextBox tbsearch;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.ComboBox cboCategory;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox tbImage;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSelectFile;
        private System.Windows.Forms.PictureBox pbImage;
    }
}